export const imageStyles = [
  { id: "pixar3d", label: "Pixar 3D", prompt: "3D stylized cartoon character with smooth textures and studio lighting" },
  { id: "legominifig", label: "Lego Minifig", prompt: "Modular plastic toy minifigure in a brick-built scene" },
  { id: "funkopop", label: "Funko Pop", prompt: "Chibi-style vinyl figure with an oversized head and black button eyes" },
  { id: "cyberpunk", label: "Cyberpunk", prompt: "Futuristic neon look with cybernetic implants and holographic HUDs" },
  { id: "vintage80s", label: "Vintage 80s", prompt: "Retro 1980s 35mm film photograph with grain and period aesthetics" },
  { id: "gtaart", label: "GTA Art", prompt: "Cel-shaded digital loading screen art style with heavy line work" },
  { id: "ice_sculpture", label: "Ice Sculpture", prompt: "Carved translucent crystalline ice sculpture with refracted light" },
  { id: "bobblehead", label: "Bobblehead", prompt: "Dashboard figurine with an exaggerated large head on a metal spring" },
  { id: "fresco", label: "Fresco", prompt: "Distressed Renaissance wall mural on weathered plaster" },
  { id: "steampunk", label: "Steampunk", prompt: "Victorian aesthetic with exposed brass gears, pipes, and leather" },
  { id: "anime", label: "Anime", prompt: "Classic Japanese 2D animation with clean linework and cel shading" },
  { id: "claymation", label: "Claymation", prompt: "Stop-motion plasticine clay model with tactile handcrafted textures" },
  { id: "pixelart", label: "Pixel Art", prompt: "16-bit retro video game sprite art with a restricted color palette" },
  { id: "superhero_comic", label: "Superhero Comic", prompt: "Dynamic comic book splash page with halftone dot shading" },
  { id: "timburton", label: "Tim Burton", prompt: "Gothic fairytale aesthetic with slender silhouettes and dark tones" },
  { id: "studioghibli", label: "Studio Ghibli", prompt: "Whimsical hand-painted anime style with lush watercolor backgrounds" },
  { id: "chibi", label: "Chibi", prompt: "Cute miniature proportions with a huge head and tiny body" },
  { id: "marblebust", label: "Marble Bust", prompt: "Classical Greco-Roman statue carved from white marble" },
  { id: "origami", label: "Origami", prompt: "Geometric paper sculpture folded from crisp textured paper" },
  { id: "woodcarving", label: "Wood Carving", prompt: "Rustic hand-carved wooden figure showing natural wood grain" },
  { id: "feltplushie", label: "Felt Plushie", prompt: "Hand-sewn felt plush toy with visible needlework" },
  { id: "neonnoir", label: "Neon Noir", prompt: "Moody rainy detective scene lit by glowing neon streetlights" },
  { id: "caricature", label: "Caricature", prompt: "Exaggerated humorous portrait highlighting distinct facial features" },
  { id: "oilpainting", label: "Oil Painting", prompt: "Classical oil on canvas portrait with visible brushstrokes" },
  { id: "watercolor", label: "Watercolor", prompt: "Fluid watercolor painting with soft edge bleeds on paper" },
  { id: "vaporwave", label: "Vaporwave", prompt: "1990s retro surrealism with pastel pink, teal, and digital grids" },
  { id: "mecharobot", label: "Mecha Robot", prompt: "Armored sci-fi mech warrior with mechanical plating" },
  { id: "lowpoly", label: "Low Poly", prompt: "Minimalist 3D faceted geometric polygon mesh" },
  { id: "popart", label: "Pop Art", prompt: "Bold screen-printed Pop Art style with high-contrast color blocks" },
  { id: "papercut", label: "Papercut", prompt: "Multi-layered shadow box cut out of stacked colored craft paper" },
  { id: "stainedglass", label: "Stained Glass", prompt: "Cathedral stained-glass window with thick dark lead borders" },
  { id: "hologram", label: "Hologram", prompt: "Semi-transparent glowing cyan sci-fi holographic projection" },
  { id: "zombify", label: "Zombify", prompt: "Grungy post-apocalyptic undead zombie creature" },
  { id: "medievalknight", label: "Medieval Knight", prompt: "Royal knight in ornate polished plate armor" },
  { id: "bronzesculpture", label: "Bronze Sculpture", prompt: "Patinated antique bronze monument with polished highlights" },
  { id: "gothicart", label: "Gothic Art", prompt: "Dark Victorian oil portrait with velvet textures and deep shadows" },
  { id: "synthwave", label: "Synthwave", prompt: "1980s retro-futuristic scene with glowing grids and chrome accents" },
  { id: "tarotcard", label: "Tarot Card", prompt: "Esoteric mystical card illustration with gold foil borders" },
  { id: "chalkboard", label: "Chalkboard", prompt: "Detailed chalk illustration and lettering on a dark slate board" },
  { id: "barbiebox", label: "Barbie Box", prompt: "Mint-in-box fashion doll in clear plastic retail packaging" },
  { id: "glitchart", label: "Glitch Art", prompt: "Distorted digital glitch effect with VHS scanlines and chromatic split" },
  { id: "simpsonized", label: "Simpsonized", prompt: "Yellow-skinned animated cartoon character in iconic comedy style" },
  { id: "streetgraffiti", label: "Street Graffiti", prompt: "Vibrant spray-painted mural on a gritty brick wall" },
  { id: "linocut", label: "Linocut", prompt: "High-contrast relief print with sharp gouged linework" },
  { id: "sandsculpture", label: "Sand Sculpture", prompt: "Realistic sand sculpture sculpted on a beach" },
  { id: "isometric", label: "Isometric", prompt: "Miniature 3D room diorama viewed from an isometric angle" },
  { id: "embroidery", label: "Embroidery", prompt: "Textured colorful thread embroidery stitched onto coarse fabric" },
  { id: "rubberhose", label: "Rubber Hose", prompt: "1930s monochrome vintage cartoon with bendy limbs" },
  { id: "stainedclay", label: "Stained Clay", prompt: "Glazed ceramic sculpture with traditional mosaic motifs" },
  { id: "waxfigure", label: "Wax Figure", prompt: "Hyper-realistic museum wax figure with lifelike skin texture" },
  { id: "modelkit", label: "Model Kit", prompt: "Unassembled plastic model parts attached to runner sprues" },
  { id: "snowglobe", label: "Snow Globe", prompt: "Miniature scene enclosed inside a swirling glass snow globe" },
  { id: "clockwork", label: "Clockwork", prompt: "Vintage mechanical automaton with brass dials and wind-up keys" },
  { id: "toysoldier", label: "Toy Soldier", prompt: "Hand-painted vintage cast metal miniature soldier" },
  { id: "jadecarving", label: "Jade Carving", prompt: "Semi-translucent carved green jade figurine" },
  { id: "obsidian", label: "Obsidian", prompt: "Glossy black volcanic glass carving with razor-sharp facets" },
  { id: "amberstone", label: "Amber Stone", prompt: "Subject preserved inside translucent golden fossil amber" },
  { id: "porcelain", label: "Porcelain", prompt: "Fine glossy porcelain doll with delicate painted details" },
  { id: "artdeco", label: "Art Deco", prompt: "1920s luxury aesthetic with geometric symmetry and gold filigree" },
  { id: "artnouveau", label: "Art Nouveau", prompt: "Organic curves, botanical borders, and flowing decorative lines" },
  { id: "ukiyoe", label: "Ukiyo-e", prompt: "Traditional Japanese Edo-period woodblock print with flat inks" },
  { id: "byzantine", label: "Byzantine", prompt: "Medieval religious icon painting featuring gilded gold leaf" },
  { id: "egyptianrelief", label: "Egyptian Relief", prompt: "Carved sandstone bas-relief mural from ancient Egypt" },
  { id: "silhouette", label: "Silhouette", prompt: "Stark solid black cutout profile over a bright gradient backdrop" },
  { id: "blueprint", label: "Blueprint", prompt: "Technical drafting schematic with white lines on blue paper" },
  { id: "wireframe", label: "Wireframe", prompt: "Glowing vector polygon mesh in a virtual grid environment" },
  { id: "xray", label: "X-Ray", prompt: "Translucent skeletal radiograph revealing internal anatomy" },
  { id: "mangapanel", label: "Manga Panel", prompt: "High-contrast Japanese manga panel with dynamic speed lines" },
  { id: "charcoaldrawing", label: "Charcoal Drawing", prompt: "Expressive smudged charcoal sketch with deep dark tones" },
  { id: "amigurumi", label: "Amigurumi", prompt: "Knitted miniature yarn plushie with stitched details" },
  { id: "asciiart", label: "ASCII Art", prompt: "Monochromatic portrait formed entirely from typography characters" },
  { id: "zentangle", label: "Zentangle", prompt: "Dense ink illustration filled with repetitive abstract patterns" },
  { id: "lightpainting", label: "Light Painting", prompt: "Long-exposure photograph tracing glowing light streaks in dark" },
  { id: "popupbook", label: "Pop-Up Book", prompt: "3D folded papercraft mechanism rising from an open storybook" },
  { id: "mosaic", label: "Mosaic", prompt: "Artwork assembled from thousands of tiny cut ceramic tesserae" },
  { id: "etchasketch", label: "Etch A Sketch", prompt: "Monochromatic continuous single-line mechanical drawing" },
  { id: "cubism", label: "Cubism", prompt: "Deconstructed multi-perspective cubist painting" },
  { id: "solarpunk", label: "Solarpunk", prompt: "Bright eco-futuristic scene blending renewable tech and nature" },
  { id: "filmnoir", label: "Film Noir", prompt: "1940s black-and-white cinematic frame with sharp shadow blinds" },
  { id: "crayon", label: "Crayon", prompt: "Heavy wax crayon drawing with rough textured strokes" },
  { id: "daguerreotype", label: "Daguerreotype", prompt: "19th-century silver-plate antique photograph in a velvet case" },
  { id: "gouache", label: "Gouache", prompt: "Matte opaque gouache painting with flat, saturated color blocks" },
  { id: "balloonanimal", label: "Balloon Animal", prompt: "Sculpted twisted glossy latex balloons" },
  { id: "psychedelic", label: "Psychedelic", prompt: "1960s poster with melting forms, rainbow hues, and optic swirls" },
  { id: "biopunk", label: "Biopunk", prompt: "Sci-fi biomechanical design featuring glowing organic tissues" },
  { id: "vectorflat", label: "Vector Flat", prompt: "Clean 2D flat minimalist vector graphic with solid shapes" },
  { id: "crossstitch", label: "Cross Stitch", prompt: "Pixelated needlepoint pattern stitched on grid linen" },
  { id: "soapstone", label: "Soapstone", prompt: "Smooth matte hand-carved soapstone statuette" },
  { id: "pinhole", label: "Pinhole", prompt: "Soft-focus experimental photo with natural vignetting" },
  { id: "neonwire", label: "Neon Wire", prompt: "Minimalist figure contoured with glowing electroluminescent wire" },
  { id: "sandblastedglass", label: "Sandblasted Glass", prompt: "Frosted glass panel with etched relief artwork" },
  { id: "paperplate", label: "Paper Plate", prompt: "Elementary school craft made of paper plates and pipe cleaners" },
  { id: "quilling", label: "Quilling", prompt: "Filigree decorative artwork rolled from tight strips of paper" },
  { id: "vintagetravel", label: "Vintage Travel", prompt: "1950s retro lithograph tourism poster with bold typography" },
  { id: "matrixcode", label: "Matrix Code", prompt: "Digital silhouette dissolving into cascading green matrix glyphs" },
  { id: "pointillism", label: "Pointillism", prompt: "Impressionist composition painted from tiny distinct color dots" },
  { id: "pewtermini", label: "Pewter Mini", prompt: "Unpainted miniature tabletop wargaming figure" },
  { id: "inkwash", label: "Ink Wash", prompt: "Traditional East Asian Sumi-e ink brush painting" },
  { id: "retrogaming", label: "Retro Gaming", prompt: "8-bit pixelated arcade screen with CRT scanlines" },
  { id: "glassblowing", label: "Glassblowing", prompt: "Sculpted translucent hand-blown colored art glass" }
];
